box/urls.py
from django.conf.urls import url
from . import views
app_name = 'box'
urlpatterns = [
    url(r'^(?P<employee_id>[0-9]+)/further/$',views.further, name='further'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<employee_gmail_id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<employee_id>[0-9]+)/create_employee_private/$', views.create_employee_private, name='create_employee_private'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^create_employee_gmail/$', views.create_employee_gmail, name='create_employee_gmail'),
    url(r'^(?P<employee_id>[0-9]+)/scheduling/$', views.scheduling, name='scheduling'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/(?P<feedback_id>[0-9]+)/feedback/$', views.feedback, name='feedback'),
    url(r'^(?P<employee_id>[0-9]+)/interview_details/$', views.interview_details, name='interview_details'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/status/$', views.status, name='status'),
    url(r'^(?P<employee_id>[0-9]+)/update/$', views.update, name='update'),
    url(r'^(?P<employee_id>[0-9]+)/update_public/$', views.update_public, name='update_public'),
    url(r'^(?P<employee_id>[0-9]+)/update_private/$', views.update_private, name='update_private'),
    url(r'^(?P<employee_id>[0-9]+)/update_vehicle/$', views.update_vehicle, name='update_vehicle'),
    url(r'^(?P<employee_id>[0-9]+)/hr_all/$', views.hr_all, name='hr_all'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/hr_inter_all/$', views.hr_inter_all, name='hr_inter_all'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/(?P<feedback_id>[0-9]+)/inter_all/$', views.inter_all, name='inter_all'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/scheduling2/$', views.scheduling2, name='scheduling2'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/scheduling3/$', views.scheduling3, name='scheduling3'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/rescheduling1/$', views.rescheduling1, name='rescheduling1'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/rescheduling2/$', views.rescheduling2, name='rescheduling2'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/rescheduling3/$', views.rescheduling3, name='rescheduling3'),
    url(r'^(?P<employee_id>[0-9]+)/(?P<interviewee_id>[0-9]+)/rescheduling/$', views.rescheduling, name='rescheduling'),
]

coriolis_latest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings               #used when we will be uploading resumes
from django.conf.urls.static import static     #used while resume uploading

urlpatterns = [
    url(r'^admin/', admin.site.urls),
     #127.0.0.1:8000/box/
    url(r'^box/',include('box.urls')),

    url(r'^box/', include('allauth.urls') , name='social'),

]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL,documents_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.MEDIA1_URL,document_root=settings.MEDIA1_ROOT)
    urlpatterns += static(settings.MEDIA2_URL, document_root=settings.MEDIA2_ROOT)

box/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from .models import Employee_Gmail,Employee_Private,Employee_Public,Interviewee, Vehicle, Feedback
from functools import partial
DateInput = partial(forms.DateInput, {'class': 'datepicker'})

class Employee_GmailForm(forms.ModelForm):

    class Meta:
        model = Employee_Gmail

        fields = ['firstname', 'lastname', 'email']

    def clean_email(self):
        email = self.cleaned_data['email']
        if Employee_Gmail.objects.filter(email=email).exists():
            raise ValidationError("details already exists")
        return email

    def __init__(self, *args, **kwargs):
        super(Employee_GmailForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance:
            self.fields['firstname'].widget.attrs['readonly'] = True
            self.fields['lastname'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True


class Employee_PublicForm(forms.ModelForm):

    class Meta:
        model = Employee_Public
        fields = ['photo_logo','mobile_number','emergency_contact_number','emergency_contact_number1','current_address' ,'field_of_intrest']

class Employee_PrivateForm(forms.ModelForm):

    class Meta:
        model = Employee_Private
        widgets = {'date_of_birth': DateInput()}
        fields = ['date_of_birth','resume','permanent_address','pan','passport_no','passport_expiry']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

class VehicleForm(forms.ModelForm):

    class Meta:
        model= Vehicle
        fields = ['vechicle_type','vechicle_model','vechicle_number']


class IntervieweeForm(forms.ModelForm):

    class Meta:
        model= Interviewee
        fields = ['interviewee_name', 'interviewee_email_id','interviewee_resume', 'job_profile']


class Interviewee_SchedulingForm(forms.ModelForm):

    class Meta:
        model= Interviewee
        fields = ['interviewee_name', 'interviewee_email_id','interviewee_resume', 'job_profile']


class EmptyChoiceField(forms.ChoiceField):
    def __init__(self, choices=(), empty_label=None, required=True, widget=None, label=None, initial=None, help_text=None, *args, **kwargs):


        if not required and empty_label is not None:
            choices = tuple([(u'', empty_label)] + list(choices))

        super(EmptyChoiceField, self).__init__(choices=choices, required=required, widget=widget, label=label, initial=initial, help_text=help_text, *args, **kwargs)

class InterviewForm(forms.Form):
        interview_date = forms.DateField(widget=DateInput())
        interview_time= forms.TimeField()

        interviewer_email_id1 = EmptyChoiceField(choices=[(x, x) for x in (Employee_Gmail.objects.all())], required=False, empty_label="Null")

        interviewer_email_id2 = EmptyChoiceField(choices=[(x, x) for x in (Employee_Gmail.objects.all())], required=False, empty_label="Null")
        interviewer_email_id3 = EmptyChoiceField(choices=[(x, x) for x in (Employee_Gmail.objects.all())], required=False, empty_label="Null")

class Employee1_FeedbackForm(forms.ModelForm):

        class Meta:
            model = Interviewee
            fields = ['interviewee_name', 'interviewee_email_id']

        def __init__(self, *args, **kwargs):
            super(Employee1_FeedbackForm, self).__init__(*args, **kwargs)
            instance = getattr(self, 'instance', None)
            if instance:
                self.fields['interviewee_name'].widget.attrs['readonly'] = True
                self.fields['interviewee_email_id'].widget.attrs['readonly'] = True

class Employee_FeedbackForm(forms.ModelForm):

    class Meta:
        model= Feedback
        fields = ['interview_date','level','feedback']

    def __init__(self, *args, **kwargs):
        super(Employee_FeedbackForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance:
            self.fields['interview_date'].widget.attrs['readonly'] = True
            self.fields['level'].widget.attrs['readonly'] = True

class StatusForm(forms.Form):
    status = forms.ChoiceField(choices=[(x, x) for x in ('hired', 'Rejected', 'Second Round','Third Round', 'On Hold')])

class ReschedulingForm(forms.Form):
    level = forms.ChoiceField(choices=[(x, x) for x in ('Level1','Level2','Level3')])

box/views.py
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.conf import settings
from django.core.mail import send_mail
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from .forms import Employee_GmailForm,Interviewee_SchedulingForm,ReschedulingForm,Employee_PublicForm,StatusForm,Employee_PrivateForm, UserForm, Employee_FeedbackForm,Employee1_FeedbackForm, VehicleForm, IntervieweeForm, InterviewForm
from .models import Employee_Gmail , Employee_Public , Employee_Private,Vehicle, Interviewee,Feedback
RESUME_FILE_TYPES = ['pdf', 'PDF', 'doc']
INTERVIEWEE_RESUME_FILE_TYPES = ['pdf', 'PDF', 'doc']
IMAGE_FILE_TYPES = ['jpg','png','jpeg']
earlier_date = 0
earlier_time = 0


def create_employee_gmail(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/box/login/")
    else:
        e=Employee_Gmail.objects.filter(email=request.user.email)
        if len(e)==0:
            form = Employee_GmailForm(request.POST or None,
                                      initial={'firstname': request.user.first_name, 'lastname': request.user.last_name,
                                               'email': request.user.email})
            form1 = Employee_PublicForm(request.POST or None, request.FILES or None)
            if all((form.is_valid(), form1.is_valid())):
                employee6=form.save(commit=False)
                employee1 = form1.save(commit=False)
                employee1.photo_logo = request.FILES['photo_logo']
                file_type1 = employee1.photo_logo.url.split('.')[-1]
                file_type1 = file_type1.lower()
                if file_type1 not in IMAGE_FILE_TYPES:
                    context = {
                        'employee6': employee6,
                        'employee1': employee1,
                        "form": form,
                        "form1": form1,

                        'error_message': 'photo file must be jpg, jpeg, or png',
                    }
                    return render(request, 'box/create_employee_gmail.html', context)
                employee6.save()

                employee1.employee_gmail = employee6
                employee1.save()
                employee_gmails = Employee_Gmail.objects.all()
                eb = request.user.email
                for employee_gmail in employee_gmails:
                    if str(employee_gmail.email) == str(eb):

                        return HttpResponseRedirect('/box/'+ str(employee_gmail.id)+'/create_employee_private/')
            else:
                context = {
                     "form": form,
                     "form1": form1,
                 }
                return render(request, 'box/create_employee_gmail.html', context)
        else:
            emp_details = Employee_Gmail.objects.all()
            for emp_detail in emp_details:
                if str(request.user.email) == str(emp_detail.email):
                    return HttpResponseRedirect('/box/' + str(emp_detail.id) + '/create_employee_private/')


def create_employee_private(request, employee_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/box/login/")
    else:
        e = get_object_or_404(Employee_Gmail, pk=employee_id)
        employee_privates = Employee_Private.objects.all()

        for employee_private11 in employee_privates:
            if str(employee_private11.employee_gmail.email)== str(e.email):
                return HttpResponseRedirect("/box/" + str(e.id) + "/further/")


        form2 = Employee_PrivateForm(request.POST or None, request.FILES or None)
        form4 = VehicleForm(request.POST or None, request.FILES or None)
        if all((form2.is_valid(), form4.is_valid())):
            employee2 = form2.save(commit=False)
            employee4 = form4.save(commit=False)
            employee2.employee_gmail = e
            employee4.employee_gmail = e

            employee2.resume = request.FILES['resume']
            file_type2 = employee2.resume.url.split('.')[-1]
            file_type2 = file_type2.lower()
            if file_type2 not in RESUME_FILE_TYPES:
                context = {
                    'e': e,

                    'employee2': employee2,

                    'employee4': employee4,
                    "form2": form2,

                    "form4": form4,
                    'error_message': 'Resume file must be pdf, PDF, or doc',
                }
                return render(request, 'box/create_employee_private.html', context)
            employee2.save()
            employee4.save()

            return HttpResponseRedirect("/box/" + str(e.id) + "/further/")
        else:
            context = {
                'e': e,
                "form2": form2,

                "form4": form4
            }
            return render(request, 'box/create_employee_private.html', context)


def further(request,employee_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/box/login/")
    else:

        employee_gmails = Employee_Gmail.objects.all()
        employee_privates = Employee_Private.objects.all()
        e = get_object_or_404(Employee_Gmail, pk=employee_id)
        for employee_gmail in employee_gmails:
            for employee_private in employee_privates:
                if str(employee_gmail.email) == str(e.email) and str(employee_private.employee_gmail) == str(e.email):
                    emp = employee_gmail.firstname
                    query = request.GET.get("q")
                    if query:
                        employee_gmails = employee_gmails.filter(
                        Q(firstname__icontains=query) |
                        Q(lastname__icontains=query)
                        ).distinct()
                        return render(request, 'box/further.html', {
                        'employee_gmails': employee_gmails,
                        'employee_private': employee_private,
                        'emp':emp,
                            'e':e,
                        })
                    else:
                        return render(request, 'box/further.html', {'e':e,'employee_private': employee_private,'employee_gmails': employee_gmails, 'emp':emp })


def detail(request , employee_id,employee_gmail_id ):
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/box/login/")
    else:
        employee_id_taken = get_object_or_404(Employee_Gmail, pk=employee_id)
        employee_gmail = get_object_or_404(Employee_Gmail, pk=employee_gmail_id)
        employee_publics= Employee_Public.objects.all()
        for employee_public in employee_publics:
            if str(employee_gmail.email) ==  str(employee_public.employee_gmail):
                employee_vechicles= Vehicle.objects.all()
                for employee_vechicle in employee_vechicles:
                    if str(employee_gmail.email) == str(employee_vechicle.employee_gmail):
                        return render(request, 'box/detail.html', {'employee_id_taken':employee_id_taken,'employee_gmail': employee_gmail,'employee_vechicle':employee_vechicle,'employee_public':employee_public})


def update (request, employee_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/box/login/")
    else:
        employee_id_taken = get_object_or_404(Employee_Gmail, pk=employee_id)
        return render (request,'box/update.html',{'employee_id_taken':employee_id_taken})


def update_public(request , employee_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect("/box/login/")
    else:
        employee_id_taken = get_object_or_404(Employee_Gmail, pk=employee_id)
        vehicles =Employee_Public.objects.all()
        for vehicle11 in vehicles:
            if str(vehicle11.employee_gmail.email) == str(employee_id_taken.email):
                form = Employee_PublicForm(request.POST or None, request.FILES or None,
                                   initial={'photo_logo': vehicle11.photo_logo,
                                            'mobile_number': vehicle11.mobile_number,
                                            'emergency_contact_number': vehicle11.emergency_contact_number,
                                            'emergency_contact_number1': vehicle11.emergency_contact_number1,
                                            'current_address': vehicle11.current_address,
                                            'field_of_intrest': vehicle11.field_of_intrest,
                                            })
                if form.is_valid():
                    update_public = form.save(commit=False)

                    Employee_Publics = Employee_Public.objects.all()
                    for Employee_Public1 in Employee_Publics:
                        if str(employee_id_taken.email) == str(Employee_Public1.employee_gmail.email):
                            Employee_Public1.photo_logo = update_public.photo_logo
                            Employee_Public1.mobile_number = update_public.mobile_number
                            Employee_Public1.emergency_contact_number = update_public.emergency_contact_number
                            Employee_Public1.emergency_contact_number1 = update_public.emergency_contact_number1
                            Employee_Public1.current_address = update_public.current_address
                            Employee_Public1.field_of_intrest = update_public.field_of_intrest
                            Employee_Public1.save()

                            return HttpResponseRedirect('/box/' + str(employee_id_taken.id) + '/update/')
                        context = {
                            'form': form,
                            'employee_id_taken': employee_id_taken,
                        }

                        return render(request, 'box/update_public.html', context)
                else:

box/templates/box/detail.html
{% extends 'box/base.html' %}
{% block title %}{{ employee_gmails }}{% endblock %}


{% block body %}
<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'box:detail' employee_id_taken.id  employee_gmail.id %}">
                        {% if employee_public.photo_logo %}
                            <img src="{{ employee_public.photo_logo.url }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ employee_gmail.firstname }}</h1>
                    <h1>{{ employee_gmail.lastname }}</h1>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'box:further' employee_id_taken.id %}">View All</a></li>
               <!-- <li role="presentation"><a href="{#% url 'music:create_song' album.id %#}">Add New Song</a></li>-->
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>{{ employee_gmail.firstname }}'s Public Details</h3>

                    {% if error_message %}





                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>mobile_no.</th>
                            <th>emergency_contact</th>
                            <th>emergency_contact1</th>
                        </tr>
                        </thead>

                        <tbody>

                            <tr>
                                <td>{{ employee_public.mobile_number }}</td>


                                <td>
                                    {{ employee_public.emergency_contact_number }}
                                    </td>

                                <td>
                                    {{ employee_public.emergency_contact_number1 }}</td>


                                </tr>

                        </tbody>
                        <thead>
                        <tr>
                            <th>Current Address</th>
                            <th>Field of Interest</th>
                            <th>Vehicle number</th>

                        </tr>
                        </thead>

                        <tbody>

                            <tr>
                                <td>{{ employee_public.current_address }}</td>
                                <td>{{ employee_public.field_of_intrest }}</td>
                                <td>{{ employee_vechicle.vechicle_number }}</td>


                        </tbody>

                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

box/templates/box/feedback.html
{% extends 'box/base.html' %}
{% block title %}Interview Feedback{% endblock %}

{% block design %}
    <ul class="nav navbar-nav navbar-left">

    <li>
        <a href="{% url 'box:interview_details' employee_id_taken.id %}">
            <span class="glyphicon glyphicon-arrow-left" aria-hidden="true"></span>&nbsp; back
        </a>
    </li></ul>
    <ul class="nav navbar-nav navbar-right">
    <li>
        <a href="{% url 'box:logout_user' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
        </a>
    </li></ul>
{% endblock %}

{% block body %}


<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Enter the feedback details.</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'box/form_template.html' %}
                        {% include 'box/form_template1.html' %}
                             <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button onclick="PopUp()" type="submit" class="btn btn-success">Submit</button>
                                <script>
function PopUp(){
    document.getElementByID("You have successfully").showModal();
}</script>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>



    </div>

</div>
{% endblock %}

box/templates/box/form_template4.html
{% for field in form4 %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

box/templates/box/further.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Employee details{% endblock %}</title>
    {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'box/style.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>



    <!--<script src="{#% static 'box/js/main.js' %#}"></script> -->
    <style>
         p {
    background-color: black;
           }
           p.padding {

                          padding-right: 100px;

                      }
</style>
</head>
<body>
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <!-- Header -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

        </div>

        <!-- Items -->
       <div class="collapse navbar-collapse" id="topNavBar">
               <ul class="nav navbar-nav">
                <li><a href="{% url 'box:update' e.id %}"><span class="glyphicon glyphicon-modal-window" aria-hidden="true"></span>&nbsp; Update Your Details</a></li></ul>
            <form class="navbar-form navbar-left" role="search" method="get" action="{% url 'box:further' e.id %}">
                <div class="form-group">
                    <input type="text" class="form-control" name="q" value="{{ request.GET.q }}">
                </div>
                <button type="submit" class="btn btn-default">Search</button>
            </form>
            {% block design %}
            <ul class="nav navbar-nav navbar-right">
                {%  if employee_private.hr %}
                <li>
                    <a href="{% url 'box:scheduling' e.id %}">
                        <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>&nbsp; Interview Scheduling
                    </a>
                </li>
                {% endif %}

                 <li>
                    <a href="{% url 'box:interview_details' e.id %}">
                        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>&nbsp; Interview Details
                    </a>
                </li>
                <li>
                    <a href="{% url 'box:logout_user' %}">
                        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
                    </a>
                </li>
            </ul>
            {% endblock %}
        </div>

    </div>
</nav>



<div class="albums-container container-fluid">

    <div class="row">
      <div align="center">
        <div class="col-sm-12">
            <h3>{{ emp }}'s account</h3>
        </div>
          {% if employee_gmails %}
              <p class="tabular">
                  <table border="2" width="50%">
                                        <p class="padding">

                      <tr><th>Email ID</th><th>First Name</th><th> Last Name </th></tr>
                         {% for employee_gmail in employee_gmails %}


                            <tr><td><a href="{% url 'box:detail' e.id employee_gmail.id %}"> {{ employee_gmail.email }} </a> </td><td>{{ employee_gmail.firstname}}</td><td>{{ employee_gmail.lastname}}</td></tr>


                                    </p>

                         {% endfor %}
                 </table> </p>

              </div>
          {% endif %}
      </div>
    </div>
    </div></body>

box/templates/box/rescheduling_level2.html
{% extends 'box/base.html' %}
{% block title %}Recheduling_level2{% endblock %}


{% block design %}
       <<ul class="nav navbar-nav navbar-left">

    <li>
        <a href="{% url 'box:hr_all' employee_id_taken.id %}">
            <span class="glyphicon glyphicon" aria-hidden="true"></span>&nbsp; Home
        </a>
    </li></ul>

    <ul class="nav navbar-nav navbar-right">

    <li>
        <a href="{% url 'box:logout_user' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
        </a>
    </li></ul>
{% endblock %}

{% block body %}


<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Enter the interview details for Rescheduling level 2</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'box/form_template.html' %}
                        {% include 'box/form_template1.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
              <script>


</script>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>



    </div>

</div>
{% endblock %}

box/templates/box/rescheduling_level3.html
{% extends 'box/base.html' %}
{% block title %}Rescheduling_level3{% endblock %}


{% block design %}
       <<ul class="nav navbar-nav navbar-left">

    <li>
        <a href="{% url 'box:hr_all' employee_id_taken.id %}">
            <span class="glyphicon glyphicon" aria-hidden="true"></span>&nbsp; Home
        </a>
    </li></ul>

    <ul class="nav navbar-nav navbar-right">

    <li>
        <a href="{% url 'box:logout_user' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
        </a>
    </li></ul>
{% endblock %}

{% block body %}


<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Enter the interview details for Rescheduling level 3</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'box/form_template.html' %}
                        {% include 'box/form_template1.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
              <script>


</script>
                            </div>
                        </div>
                    </form>
                </div>
             </div>
        </div>



    </div>

</div>
{% endblock %}

box/templates/box/update.html
{% extends 'box/base.html' %}
{% block title %}update Details{% endblock %}

{% block design %}
<ul class="nav navbar-nav">
    <li><a href="{% url 'box:further' employee_id_taken.id %}"> Home </a></li></ul>
    <ul class="nav navbar-nav navbar-right">
    <li>
        <a href="{% url 'box:logout_user' %}">
            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout
        </a>
    </li></ul>
{% endblock %}

{% block body %}

<ul>
    <li><a href="{% url 'box:update_private' employee_id_taken.id %}"> UPDATE PRIVATE DETAILS </a></li>
    <li>
        <a href="{% url 'box:update_public' employee_id_taken.id %}"> UPDATE PUBLIC DETAILS </a>
    </li>
    <li><a href="{% url 'box:update_vehicle' employee_id_taken.id %}"> UPDATE VEHICLE DETAILS </a>   </li>

</ul>
{% endblock %}